services:
    api:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always
        # Usar la red bridge por defecto donde está Oracle
        network_mode: bridge
        environment:
            # Asegurar que Python no almacene en búfer la salida
            - PYTHONUNBUFFERED=1
            # Sobrescribir DB_HOST para apuntar a la IP del contenedor Oracle
            - DB_HOST=172.17.0.2
