DROP TABLE detalle_orden_trabajo CASCADE CONSTRAINTS;
DROP TABLE productos_impuestos CASCADE CONSTRAINTS;
DROP TABLE reclamos CASCADE CONSTRAINTS;
DROP TABLE perfiles_permisos CASCADE CONSTRAINTS;
DROP TABLE permisos CASCADE CONSTRAINTS;
DROP TABLE perfiles CASCADE CONSTRAINTS;
DROP TABLE ordenes_trabajo CASCADE CONSTRAINTS;
DROP TABLE motos CASCADE CONSTRAINTS;
DROP TABLE productos CASCADE CONSTRAINTS;
DROP TABLE vistas CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;
DROP TABLE ot_estados CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;
DROP TABLE marcas CASCADE CONSTRAINTS;
DROP TABLE impuestos CASCADE CONSTRAINTS;
DROP TABLE excepciones CASCADE CONSTRAINTS;
DROP TABLE estados CASCADE CONSTRAINTS;
DROP TABLE clientes CASCADE CONSTRAINTS;


DROP SEQUENCE seq_impuestos;
DROP SEQUENCE seq_marcas;
DROP SEQUENCE seq_perfiles;
DROP SEQUENCE seq_permisos;
DROP SEQUENCE seq_productos;
DROP SEQUENCE seq_productos_impuestos;
DROP SEQUENCE seq_reclamos;
DROP SEQUENCE seq_roles;